slack:
  bot_token: SLACK_BOT_TOKEN
  app_token: SLACK_APP_TOKEN
  ccd:
    report_channel: CCD_SLACK_REPORT_CHANNEL
    report_channel_id: CCD_SLACK_REPORT_CHANNEL_ID
  cfts:
    report_channel: CFTS_SLACK_REPORT_CHANNEL
    report_channel_id: CFTS_SLACK_REPORT_CHANNEL_ID

jira:
  username: JIRA_USERNAME
  api_token: JIRA_API_TOKEN
  ccd:
    start_transition_id: CCD_JIRA_START_TRANSITION_ID
    done_transition_id: CCD_JIRA_DONE_TRANSITION_ID
    project: CCD_JIRA_PROJECT
    issue_type_id: CCD_JIRA_ISSUE_TYPE_ID
    issue_type_name: CCD_JIRA_ISSUE_TYPE_NAME
  cfts:
    start_transition_id: CFTS_JIRA_START_TRANSITION_ID
    done_transition_id: CFTS_JIRA_DONE_TRANSITION_ID
    project: CFTS_JIRA_PROJECT
    issue_type_id: CFTS_JIRA_ISSUE_TYPE_ID
    issue_type_name: CFTS_JIRA_ISSUE_TYPE_NAME
