# defaults are setup for the platform engineering slack workspace
slack:
  #bot_token: no default
  #app_token: no default
  ccd:
    report_channel: bot-test
    report_channel_id: C01KHKNJUKE
  cfts:
    report_channel: bot-test
    report_channel_id: C01KHKNJUKE

jira:
  #username: no default
  #api_token: no default
  ccd:
    start_transition_id: 21
    done_transition_id: 41
    project: SBOX
    issue_type_id: Bug
    issue_type_name: 10900
  cfts:
    start_transition_id: 21
    done_transition_id: 41
    project: SBOX
    issue_type_id: Bug
    issue_type_name: 1090
